### ISSUE TITLE
error on integrated assay 

### ISSUE THREAD

**Issue by QSong-github** [bioturing/rBCS#22]
Thanks for providing this conversion tool. I met some error when I am trying to input the integrated Seurat assay. Here are the commands and errors. 
Could you give some hints on this?

 > ExportSeurat(br.combined, "br_sc_converted.bcs",                                                                                                                                      
                            unique.limit = 200, # Allow at most 200 unique in a categorical metadata                                                                                                          
                            clustering.name = "majorCellType", # Use `my_cluster` as the clustering result                                                                                                    
                            raw.rna = "RNA", # Assay that has raw count of RNA                                                                                                                                
                           norm.rna = "integrated", # Assay that has normalized count of RNA                                                                                                                 
 )                  
                                                                                                                                                                   
 [2021-10-07 12:46:06] Initializing...
 [2021-10-07 12:46:06] Extracting expressions...
 Error in dimnamesGets(x, value) :
   invalid dimnames given for “dgCMatrix” object

**Comment by bioturing** [comment]
This thread is closed due to inactivity. Feel free to open again if you need to discuss more.
